# Generated by Django 5.1.6 on 2025-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
